const FANTASTICAL_DATA = {

  magicSystems: [
    {
      id: "ancient_elemental",
      name: "Ancient / Elemental",
      era: "Ancient",
      description: "Raw, primal magic drawn from the natural world. Earth, fire, water, and air converge through ritualistic invocation, channeled by runes, stone circles, and spoken incantations older than written language.",
      visuals: { particleType: "Dust motes, embers, water droplets, leaf fragments", glowStyle: "Warm, pulsing inner glow with organic falloff", movementPattern: "Slow spirals, rising columns, ground-hugging waves", edgeQuality: "Soft, diffused, natural", opacity: "Semi-transparent with dense core", intensity: "Builds gradually to crescendo" },
      colors: { primary: "#8B6914", secondary: "#2E7D32", accent: "#D84315", ambient: "#1B5E20" },
      sound: { description: "Deep earth rumbles layered with wind howls and crackling fire", layers: ["Sub-bass earth drone", "Mid-range wind texture", "High crackling embers"], frequencyRange: "20Hz-8kHz", organic: true },
      promptKeywords: ["ancient magic", "elemental sorcery", "rune glow", "earth magic particles", "mystical forest light", "stone circle ritual", "primal energy", "nature magic VFX", "glowing runes", "organic magic particles", "druidic spell"],
      famousExamples: ["Lord of the Rings - Gandalf's staff magic", "Willow - Bavmorda's ritual", "The Green Knight - nature magic"],
      tags: { mood: ["mysterious", "ancient", "powerful"], energy: "low", era: "ancient", complexity: "medium", scale: "large" }
    },
    {
      id: "modern_urban",
      name: "Modern / Urban",
      era: "Contemporary",
      description: "Geometric, precise magic manifesting as mandalas, glyphs, and hard-light constructs. Practiced through learned gestures and intellectual mastery, it bends reality with mathematical precision in urban environments.",
      visuals: { particleType: "Geometric shards, light fractals, mandala rings", glowStyle: "Sharp-edged neon with clean falloff", movementPattern: "Rapid rotation, expanding rings, snapping into place", edgeQuality: "Hard, crisp, defined", opacity: "Bright and opaque with translucent edges", intensity: "Instant activation, sustained output" },
      colors: { primary: "#FF6F00", secondary: "#E65100", accent: "#FFD600", ambient: "#BF360C" },
      sound: { description: "Crystalline chimes over electrical hum with sharp activation sounds", layers: ["Electrical hum base", "Glass chime texture", "Sharp snap accents"], frequencyRange: "200Hz-16kHz", organic: false },
      promptKeywords: ["geometric magic", "mandala spell circle", "urban sorcery", "hard light construct", "magical glyphs floating", "neon spell effects", "Doctor Strange style magic", "arcane geometry", "spell shield", "portal magic"],
      famousExamples: ["Doctor Strange - mirror dimension magic", "Harry Potter - wand spells", "The Sorcerer's Apprentice"],
      tags: { mood: ["dynamic", "intellectual", "precise"], energy: "high", era: "modern", complexity: "high", scale: "medium" }
    },
    {
      id: "futuristic_tech",
      name: "Futuristic / Tech",
      era: "Futuristic",
      description: "Technology indistinguishable from magic. Holographic interfaces, force fields, energy manipulation through neural implants or telekinetic amplifiers. Clean, efficient, and devastatingly powerful.",
      visuals: { particleType: "Data streams, holographic fragments, energy pulses", glowStyle: "Cool, even emission with digital flicker", movementPattern: "Linear trajectories, grid-aligned, instant teleportation", edgeQuality: "Pixel-sharp, sometimes glitching", opacity: "Translucent holographic with scanlines", intensity: "Constant with burst peaks" },
      colors: { primary: "#00B0FF", secondary: "#0091EA", accent: "#00E5FF", ambient: "#01579B" },
      sound: { description: "Synthesized tonal sweeps with digital processing and electromagnetic hum", layers: ["Low electromagnetic drone", "Mid-range digital pulse", "High-frequency data chirps"], frequencyRange: "80Hz-20kHz", organic: false },
      promptKeywords: ["sci-fi magic", "holographic interface", "force field energy", "tech sorcery", "cybernetic power", "energy beam", "futuristic spell", "neural magic", "plasma energy", "telekinetic force", "HUD magic overlay"],
      famousExamples: ["Star Wars - The Force", "Tron Legacy - disc and light powers", "The Matrix - code manipulation"],
      tags: { mood: ["sleek", "powerful", "cold"], energy: "high", era: "futuristic", complexity: "high", scale: "medium" }
    },
    {
      id: "robotic_cybernetic",
      name: "Robotic / Cybernetic",
      era: "Cyberpunk",
      description: "Mechanical augmentation meets arcane energy. Circuit-like patterns pulse through artificial bodies, magic channeled through prosthetics, implants, and bio-mechanical symbiosis. Glitchy, unstable, raw.",
      visuals: { particleType: "Circuit sparks, binary cascades, mechanical fragments", glowStyle: "Strobing, irregular pulses with static interference", movementPattern: "Jerky, mechanical articulation with smooth servo movements", edgeQuality: "Glitchy, pixelated edges with scan artifacts", opacity: "Flickering between solid and transparent", intensity: "Unstable, surging" },
      colors: { primary: "#F50057", secondary: "#D500F9", accent: "#76FF03", ambient: "#1A237E" },
      sound: { description: "Servo whines mixed with electrical arcing and corrupted digital audio", layers: ["Mechanical servo base", "Electrical arc texture", "Glitch noise sweetener"], frequencyRange: "40Hz-18kHz", organic: false },
      promptKeywords: ["cybernetic magic", "circuit pattern glow", "mechanical sorcery", "glitch magic effect", "bio-mechanical energy", "cyberpunk spell", "augmented reality magic", "neon circuit lines", "robotic transformation", "tech-organic fusion"],
      famousExamples: ["Ghost in the Shell - cybernetic abilities", "Alita Battle Angel - berserker body", "Upgrade - STEM powers"],
      tags: { mood: ["chaotic", "intense", "unstable"], energy: "high", era: "cyberpunk", complexity: "high", scale: "small" }
    },
    {
      id: "dark_forbidden",
      name: "Dark / Forbidden",
      era: "Timeless",
      description: "Corrupted, consuming magic drawn from shadow, decay, and forbidden knowledge. It devours light, twists flesh, and leaves corruption in its wake. Beautiful in its horror, addictive in its power.",
      visuals: { particleType: "Black smoke tendrils, shadow fragments, decaying embers", glowStyle: "Inverse glow — absorbs surrounding light", movementPattern: "Creeping tendrils, sudden lashes, gravitational pull", edgeQuality: "Ragged, torn, bleeding into surroundings", opacity: "Dense, light-absorbing core with wispy edges", intensity: "Slow build to overwhelming" },
      colors: { primary: "#4A148C", secondary: "#1B0033", accent: "#76FF03", ambient: "#0D0D0D" },
      sound: { description: "Reversed reverbs over sub-bass drones with whispering voices", layers: ["Sub-bass oppressive drone", "Reversed reverb whispers", "Dissonant high-frequency accents"], frequencyRange: "15Hz-12kHz", organic: true },
      promptKeywords: ["dark magic", "shadow sorcery", "forbidden spell", "necromancy VFX", "dark energy tendrils", "corrupted magic", "black smoke magic", "void energy", "cursed spell effect", "malevolent aura", "dark ritual"],
      famousExamples: ["Harry Potter - Voldemort's dark magic", "Lord of the Rings - Sauron's influence", "Maleficent - curse magic"],
      tags: { mood: ["dark", "menacing", "corrupted"], energy: "low", era: "timeless", complexity: "medium", scale: "large" }
    },
    {
      id: "celestial_divine",
      name: "Celestial / Divine",
      era: "Mythological",
      description: "Power drawn from the cosmos, the divine, or higher planes of existence. Overwhelming radiance, constellation patterns, and golden light that inspires awe and transcendence. The magic of gods and cosmic entities.",
      visuals: { particleType: "Star motes, golden light rays, constellation lines, nebula wisps", glowStyle: "Brilliant radiance with volumetric god rays", movementPattern: "Descending from above, expanding halos, orbital patterns", edgeQuality: "Bloom-heavy, ethereal, overwhelming", opacity: "Intensely bright core fading to divine haze", intensity: "Overwhelming constant radiance" },
      colors: { primary: "#FFD700", secondary: "#FFF8E1", accent: "#B388FF", ambient: "#1A237E" },
      sound: { description: "Celestial choir over deep cosmic resonance with shimmering bell tones", layers: ["Deep cosmic resonance base", "Ethereal choir texture", "Crystal bell sweetener"], frequencyRange: "60Hz-20kHz", organic: true },
      promptKeywords: ["celestial magic", "divine power", "golden god rays", "cosmic energy", "constellation magic", "heavenly light", "mythological power", "astral projection", "divine radiance", "cosmic sorcery", "transcendent glow"],
      famousExamples: ["Thor - Bifrost and lightning powers", "Eternals - cosmic energy", "Clash of the Titans - Zeus powers"],
      tags: { mood: ["awe", "heroic", "transcendent"], energy: "high", era: "mythological", complexity: "low", scale: "large" }
    }
  ],

  cameraMovements: [
    { id: "dolly_in", name: "Dolly In", description: "Camera physically moves toward the subject on a track or dolly. Creates increasing intimacy and focus, drawing the viewer into the emotional state of the character.", emotionalEffect: ["intimacy", "tension", "focus", "revelation"], speed: "variable", bestFor: ["emotional close-ups", "building tension", "key revelations", "spell casting moments"], promptKeywords: ["dolly in shot", "push in", "approaching camera"], tags: { mood: ["intimate", "intense"], intensity: "medium", scale: "small" } },
    { id: "dolly_out", name: "Dolly Out", description: "Camera retreats from the subject, revealing the surrounding environment. Creates a sense of isolation, abandonment, or awe as the world opens up.", emotionalEffect: ["isolation", "revelation", "epic", "vulnerability"], speed: "variable", bestFor: ["revealing landscapes", "showing isolation", "aftermath shots", "world-building reveals"], promptKeywords: ["dolly out shot", "pull back", "retreating camera"], tags: { mood: ["epic", "lonely"], intensity: "medium", scale: "large" } },
    { id: "truck", name: "Truck (Lateral)", description: "Camera moves laterally, parallel to the subject. Follows action smoothly or reveals new information across the frame.", emotionalEffect: ["flow", "continuity", "exploration", "energy"], speed: "medium", bestFor: ["following characters", "battle sequences", "revealing environments", "walking conversations"], promptKeywords: ["tracking shot", "lateral movement", "side tracking"], tags: { mood: ["dynamic", "flowing"], intensity: "medium", scale: "medium" } },
    { id: "pedestal", name: "Pedestal (Vertical)", description: "Camera moves vertically up or down while staying in place. Pedestal up reveals grandeur; pedestal down creates descent or submission.", emotionalEffect: ["power", "revelation", "awe", "submission"], speed: "slow", bestFor: ["revealing tall structures", "character introductions", "power dynamics", "descending into dungeons"], promptKeywords: ["pedestal shot", "vertical camera movement", "tilt reveal"], tags: { mood: ["powerful", "grand"], intensity: "low", scale: "large" } },
    { id: "pan", name: "Pan", description: "Camera rotates horizontally on a fixed axis. Surveys environments, follows action, or connects two subjects in the same space.", emotionalEffect: ["exploration", "connection", "surveillance", "anticipation"], speed: "variable", bestFor: ["environment surveys", "connecting characters", "reaction reveals", "landscape panoramas"], promptKeywords: ["pan shot", "horizontal pan", "sweeping pan"], tags: { mood: ["exploratory", "observant"], intensity: "low", scale: "medium" } },
    { id: "tilt", name: "Tilt", description: "Camera rotates vertically on a fixed axis. Tilt up conveys power and grandeur; tilt down suggests smallness or discovery.", emotionalEffect: ["power", "grandeur", "discovery", "intimidation"], speed: "slow", bestFor: ["revealing height of creatures", "showing character power", "cathedral interiors", "looking into chasms"], promptKeywords: ["tilt up shot", "tilt down", "vertical reveal"], tags: { mood: ["powerful", "ominous"], intensity: "medium", scale: "large" } },
    { id: "crane", name: "Crane / Jib", description: "Camera sweeps through space on an elevated arm, capable of dramatic vertical and horizontal arcs. Creates godlike perspective and cinematic grandeur.", emotionalEffect: ["epic", "grandeur", "transcendence", "omniscience"], speed: "slow", bestFor: ["establishing shots", "battle overviews", "character departures", "magical ascension scenes"], promptKeywords: ["crane shot", "jib shot", "sweeping aerial", "elevated camera movement"], tags: { mood: ["epic", "grand", "heroic"], intensity: "high", scale: "large" } },
    { id: "steadicam", name: "Steadicam / Gimbal", description: "Smooth, floating camera movement that follows subjects through space. Creates an immersive, dreamlike quality — the audience becomes a silent observer gliding through the scene.", emotionalEffect: ["immersion", "flow", "dreamlike", "pursuit"], speed: "medium", bestFor: ["following through corridors", "ritual sequences", "exploration scenes", "one-take action"], promptKeywords: ["steadicam shot", "smooth tracking", "floating camera", "gimbal shot"], tags: { mood: ["immersive", "flowing"], intensity: "medium", scale: "medium" } },
    { id: "handheld", name: "Handheld", description: "Camera held by the operator, producing organic shake and imperfection. Creates raw urgency, documentary realism, and visceral energy.", emotionalEffect: ["urgency", "chaos", "realism", "anxiety"], speed: "fast", bestFor: ["battle scenes", "chase sequences", "panic moments", "transformation pain"], promptKeywords: ["handheld camera", "shaky cam", "documentary style", "raw footage"], tags: { mood: ["chaotic", "urgent", "raw"], intensity: "high", scale: "small" } },
    { id: "drone_aerial", name: "Drone / Aerial", description: "High-altitude sweeping movements impossible with ground-based equipment. Reveals the full scope of fantasy landscapes, armies, and magical phenomena from above.", emotionalEffect: ["epic", "scale", "freedom", "omniscience"], speed: "variable", bestFor: ["landscape reveals", "army overviews", "dragon flights", "magical storms from above"], promptKeywords: ["aerial shot", "drone shot", "bird's eye view", "overhead sweeping"], tags: { mood: ["epic", "free", "vast"], intensity: "medium", scale: "large" } },
    { id: "zoom_in", name: "Zoom In", description: "Lens focal length changes to magnify the subject without moving the camera. Creates sudden focus and urgency — different feel from dolly due to perspective compression.", emotionalEffect: ["surprise", "urgency", "focus", "alarm"], speed: "fast", bestFor: ["sudden realizations", "spotting danger", "comedic beats", "magical activation"], promptKeywords: ["zoom in", "snap zoom", "crash zoom"], tags: { mood: ["urgent", "surprising"], intensity: "high", scale: "small" } },
    { id: "vertigo_effect", name: "Vertigo Effect (Dolly Zoom)", description: "Camera dollies in while zooming out (or vice versa). The background warps while the subject stays the same size. Creates profound disorientation and psychological unease.", emotionalEffect: ["disorientation", "dread", "realization", "psychological"], speed: "slow", bestFor: ["horrifying revelations", "curse effects", "reality warping", "character shock moments"], promptKeywords: ["dolly zoom", "vertigo effect", "zolly shot", "background warp"], tags: { mood: ["unsettling", "psychological"], intensity: "high", scale: "small" } },
    { id: "whip_pan", name: "Whip Pan", description: "Extremely fast horizontal pan creating motion blur. Used for sudden transitions, surprise reveals, or conveying supernatural speed.", emotionalEffect: ["surprise", "energy", "transition", "speed"], speed: "fast", bestFor: ["spell casting transitions", "time jumps", "surprise attacks", "comedic timing"], promptKeywords: ["whip pan", "swish pan", "snap turn", "fast pan transition"], tags: { mood: ["energetic", "surprising"], intensity: "high", scale: "small" } },
    { id: "orbit", name: "Orbit / Arc", description: "Camera circles around the subject, maintaining consistent distance. Creates a sense of importance, examination, or building dramatic tension around a central figure.", emotionalEffect: ["importance", "examination", "tension", "heroic"], speed: "slow", bestFor: ["hero moments", "villain reveals", "ritual circles", "power-up sequences"], promptKeywords: ["orbit shot", "arc shot", "circular tracking", "revolving camera"], tags: { mood: ["heroic", "dramatic", "important"], intensity: "medium", scale: "medium" } }
  ],

  lenses: [
    { id: "ultra_wide", name: "Ultra Wide", focalRange: "10-16mm", characteristics: { distortion: "Strong barrel distortion, curved lines", compression: "Extreme expansion of space", depthOfField: "Very deep — nearly everything in focus", bokeh: "Minimal", breathing: "Noticeable focus breathing" }, bestFor: ["Vast landscapes", "Claustrophobic interiors", "Disorienting POV shots", "Showing full spell effects"], visualSignature: "Expansive, distorted, immersive — makes small spaces feel vast and vast spaces feel infinite", famousUses: ["Lord of the Rings - Shire landscapes", "Mad Max Fury Road - chase POV"], promptKeywords: ["ultra wide angle", "fisheye lens", "distorted wide shot", "expansive perspective"], tags: { intimacy: "low", scale: "epic", style: "dramatic" } },
    { id: "wide", name: "Wide Angle", focalRange: "17-24mm", characteristics: { distortion: "Moderate wide distortion", compression: "Expanded spatial relationships", depthOfField: "Deep focus", bokeh: "Subtle", breathing: "Moderate" }, bestFor: ["Establishing shots", "Group scenes", "Action choreography", "Environmental storytelling"], visualSignature: "Expansive but natural — captures both character and environment with equal importance", famousUses: ["Harry Potter - Hogwarts halls", "The Lord of the Rings - battle fields"], promptKeywords: ["wide angle shot", "wide lens", "environmental framing", "24mm lens"], tags: { intimacy: "low", scale: "large", style: "natural" } },
    { id: "standard", name: "Standard / Normal", focalRange: "35-50mm", characteristics: { distortion: "Minimal — closest to human eye", compression: "Natural perspective", depthOfField: "Moderate — selective focus possible", bokeh: "Pleasant, natural circles", breathing: "Minimal" }, bestFor: ["Dialogue scenes", "Natural character work", "Documentary-style coverage", "Grounded magic scenes"], visualSignature: "Invisible lens — the audience forgets the camera exists. Pure storytelling.", famousUses: ["Most dialogue in all films", "Children of Men - long takes"], promptKeywords: ["50mm lens", "standard lens", "natural perspective", "eye-level normal lens"], tags: { intimacy: "medium", scale: "medium", style: "neutral" } },
    { id: "portrait_telephoto", name: "Portrait Telephoto", focalRange: "85-135mm", characteristics: { distortion: "None — flattering compression", compression: "Moderate background compression", depthOfField: "Shallow — beautiful subject separation", bokeh: "Creamy, circular", breathing: "Minimal" }, bestFor: ["Character close-ups", "Emotional moments", "Isolating subjects from chaos", "Intimate spell casting"], visualSignature: "Flattering, isolating, emotionally direct — the world melts away behind the subject", famousUses: ["Any close-up dialogue scene", "Portrait photography crossover"], promptKeywords: ["85mm portrait", "telephoto close-up", "shallow depth of field", "bokeh background", "compressed perspective"], tags: { intimacy: "high", scale: "small", style: "emotional" } },
    { id: "long_telephoto", name: "Long Telephoto", focalRange: "200mm+", characteristics: { distortion: "None", compression: "Extreme — flattens depth completely", depthOfField: "Paper-thin — razor-sharp subject, everything else dissolved", bokeh: "Extreme, painterly", breathing: "Very noticeable" }, bestFor: ["Surveillance/voyeuristic shots", "Compressing armies", "Isolating in chaos", "Heat haze effects"], visualSignature: "Flattened, stacked, voyeuristic — subjects seem trapped in compressed space", famousUses: ["Heat - bank robbery shootout", "War films - battlefield compression"], promptKeywords: ["telephoto lens", "long lens compression", "voyeuristic shot", "compressed depth", "200mm shot"], tags: { intimacy: "low", scale: "medium", style: "voyeuristic" } },
    { id: "macro", name: "Macro", focalRange: "60-105mm macro", characteristics: { distortion: "None", compression: "Normal at close range", depthOfField: "Extremely shallow — millimeters of focus", bokeh: "Extreme", breathing: "Very noticeable" }, bestFor: ["Magical artifacts close-up", "Potion ingredients", "Rune details", "Transformation skin detail"], visualSignature: "Reveals invisible worlds — makes the tiny feel monumental and magical", famousUses: ["Planet Earth close-ups", "Alien - face hugger detail"], promptKeywords: ["macro shot", "extreme close-up", "detail shot", "micro photography", "texture close-up"], tags: { intimacy: "extreme", scale: "tiny", style: "detailed" } },
    { id: "anamorphic", name: "Anamorphic", focalRange: "Various (2x squeeze)", characteristics: { distortion: "Characteristic oval bokeh, horizontal flares", compression: "Unique spatial quality", depthOfField: "Shallow with distinctive oval shapes", bokeh: "Oval/elliptical, signature look", breathing: "Dramatic and cinematic" }, bestFor: ["Epic widescreen compositions", "Lens flare-heavy magic", "Cinematic grandeur", "Any scene needing 'movie magic' feel"], visualSignature: "The quintessential 'cinematic' look — horizontal flares, oval bokeh, and widescreen grandeur that screams big-budget filmmaking", famousUses: ["Blade Runner 2049", "Star Wars", "The Dark Knight"], promptKeywords: ["anamorphic lens", "horizontal lens flare", "oval bokeh", "widescreen cinematic", "anamorphic distortion", "cinematic flare"], tags: { intimacy: "medium", scale: "epic", style: "cinematic" } },
    { id: "tilt_shift", name: "Tilt-Shift", focalRange: "Various (tilt mechanism)", characteristics: { distortion: "Selective plane of focus", compression: "Can appear miniaturized", depthOfField: "Controllable focus plane — sharp band through frame", bokeh: "Gradual, dreamlike", breathing: "Unique due to tilt mechanism" }, bestFor: ["Miniature effect on castles", "Dreamlike sequences", "Selective focus storytelling", "God's eye views of battles"], visualSignature: "Makes real things look like miniature models — creates a sense of omniscient observation", famousUses: ["Sherlock Holmes establishing shots", "Social Network depositions"], promptKeywords: ["tilt-shift effect", "miniature effect", "selective focus", "dreamlike lens", "model effect photography"], tags: { intimacy: "low", scale: "large", style: "stylized" } }
  ],

  cameraSystems: [
    { id: "imax", name: "IMAX", sensorSize: "70mm (15-perf)", resolution: "Up to 18K equivalent", dynamicRange: "16+ stops", visualSignature: "Unmatched resolution and scale. Images feel almost three-dimensional with extraordinary detail and immersive field of view.", bestFor: ["Epic landscapes", "Large-scale battles", "Sequences demanding audience immersion"], famousFilms: ["Dunkirk", "Interstellar", "Oppenheimer", "The Dark Knight"], frameRates: { standard: "24fps", slowMo: "48fps", highSpeed: "N/A" } },
    { id: "arri_alexa", name: "ARRI Alexa", sensorSize: "Super 35mm / Large Format", resolution: "4.5K-8K", dynamicRange: "14+ stops", visualSignature: "Legendary skin tones and organic color science. The gold standard for narrative filmmaking with a naturally filmic quality.", bestFor: ["Character-driven stories", "Nuanced lighting", "Any scene prioritizing naturalism"], famousFilms: ["Skyfall", "The Revenant", "Joker", "Dune"], frameRates: { standard: "24fps", slowMo: "120fps", highSpeed: "150fps" } },
    { id: "red", name: "RED (Monstro/Raptor)", sensorSize: "Vista Vision / Full Frame", resolution: "8K", dynamicRange: "17+ stops", visualSignature: "Ultra-sharp with clinical precision. Excels at capturing fine detail and texture. More 'digital' than ARRI but extraordinarily resolute.", bestFor: ["VFX-heavy sequences", "High detail environments", "Large format compositions"], famousFilms: ["Guardians of the Galaxy", "The Hobbit", "Gone Girl"], frameRates: { standard: "24fps", slowMo: "120fps at 4K", highSpeed: "240fps at 2K" } },
    { id: "blackmagic", name: "Blackmagic URSA", sensorSize: "Super 35mm", resolution: "4.6K-12K", dynamicRange: "13+ stops", visualSignature: "Impressive image quality accessible to independent filmmakers. Clean images with good color science at a fraction of the cost.", bestFor: ["Independent fantasy films", "Documentary", "Budget-conscious productions"], famousFilms: ["Independent productions", "Music videos", "Short films"], frameRates: { standard: "24fps", slowMo: "60fps at 4.6K", highSpeed: "120fps at 2K" } },
    { id: "sony_venice", name: "Sony Venice", sensorSize: "Full Frame 36x24mm", resolution: "6K", dynamicRange: "15+ stops", visualSignature: "Dual ISO capability with beautiful color science. Full-frame depth of field with cinematic bokeh. Excels in low light.", bestFor: ["Low-light magic scenes", "Full-frame shallow DoF work", "Night exterior fantasy"], famousFilms: ["Top Gun Maverick", "Morbius", "Bullet Train"], frameRates: { standard: "24fps", slowMo: "90fps at 4K", highSpeed: "120fps at 2K" } }
  ],

  depthOfField: [
    { id: "shallow", name: "Shallow Depth of Field", description: "Only the subject is sharp while foreground and background dissolve into creamy blur. Wide apertures (f/1.4-f/2.8) create intimate isolation.", emotionalEffect: "Intimacy, focus, emotional connection — the world narrows to this one moment", bestFor: ["Emotional close-ups", "Magical object reveals", "Character isolation in chaos"], technicalSetup: "Wide aperture (f/1.4-f/2.8), longer focal length, close subject distance" },
    { id: "deep", name: "Deep Depth of Field", description: "Everything from foreground to background remains in sharp focus. Used to show the full scope of environments and simultaneous actions.", emotionalEffect: "Scope, clarity, environmental storytelling — every detail matters", bestFor: ["Establishing wide shots", "Battle overviews", "Showing cause and effect across distance"], technicalSetup: "Narrow aperture (f/8-f/16), wide lens, hyperfocal distance" },
    { id: "rack_focus", name: "Rack Focus", description: "Focus shifts from one subject to another within a shot. Directs viewer attention and reveals new information or connections between subjects.", emotionalEffect: "Revelation, connection, shifting attention — a visual sentence with a pivot", bestFor: ["Revealing hidden threats", "Connecting two characters", "Magical cause-and-effect", "Spell target acquisition"], technicalSetup: "Shallow DoF with precise focus pull between pre-marked distances" },
    { id: "split_diopter", name: "Split Diopter", description: "Half-lens attachment that keeps two planes at different distances both in focus simultaneously. Creates an uncanny, slightly unsettling dual-focus effect.", emotionalEffect: "Unease, duality, parallel importance — two realities coexisting in one frame", bestFor: ["Showing hero and approaching villain simultaneously", "Dual perspectives", "Reality vs magic dimension"], technicalSetup: "Split diopter filter attached to lens, careful framing to hide the split line" },
    { id: "bokeh_shapes", name: "Shaped Bokeh", description: "Custom aperture shapes (stars, hearts, hexagons) that transform out-of-focus highlights into magical patterns. Purely aesthetic but powerfully atmospheric.", emotionalEffect: "Wonder, magic, fantasy atmosphere — the world itself feels enchanted", bestFor: ["Magical atmosphere", "Fairy/pixie scenes", "Enchanted forests", "Holiday/celebration magic"], technicalSetup: "Custom-cut aperture filter placed in front of lens, requires bright background highlights" }
  ],

  lightingPatterns: [
    { id: "rembrandt", name: "Rembrandt", description: "Key light at 45 degrees creates a triangle of light on the shadow side of the face. Named after the painter's signature use of chiaroscuro.", setup: "Key at 45° high and to one side, fill from opposite side at lower intensity", mood: "Dramatic, painterly, mysterious", bestFor: ["Wizard portraits", "Villain introductions", "Ancient library scenes"], keyToFillRatio: "4:1 to 8:1", tags: { drama: "high", flattery: "medium", mystery: "high" } },
    { id: "butterfly", name: "Butterfly (Paramount)", description: "Key light directly above and in front of the face, creating a butterfly-shaped shadow under the nose. Glamorous and flattering.", setup: "Key directly above camera position, high angle, fill from below or reflector", mood: "Glamorous, ethereal, divine", bestFor: ["Divine beings", "Fairy queens", "Powerful sorceresses", "Celestial entities"], keyToFillRatio: "2:1 to 4:1", tags: { drama: "medium", flattery: "high", mystery: "low" } },
    { id: "split", name: "Split Lighting", description: "Key light at 90 degrees illuminates exactly half the face, leaving the other half in complete shadow. Maximum dramatic contrast.", setup: "Key at exact 90° to one side, no fill on shadow side", mood: "Dual nature, inner conflict, deception", bestFor: ["Two-faced characters", "Moral ambiguity", "Werewolf transformation midpoints", "Corruption reveals"], keyToFillRatio: "Infinite (no fill)", tags: { drama: "extreme", flattery: "low", mystery: "high" } },
    { id: "loop", name: "Loop Lighting", description: "Key light slightly to one side and above creates a small shadow loop from the nose. Natural-looking and versatile for most face shapes.", setup: "Key at 30-45° to one side and slightly above eye level, gentle fill opposite", mood: "Natural, approachable, honest", bestFor: ["Protagonist introductions", "Mentor conversations", "Friendly magic users", "Healing scenes"], keyToFillRatio: "2:1 to 3:1", tags: { drama: "low", flattery: "high", mystery: "low" } },
    { id: "rim_silhouette", name: "Rim / Silhouette", description: "Strong backlight creates a glowing edge around the subject with the face in shadow or silhouette. Subjects become iconic shapes defined by light halos.", setup: "Strong back/rim light, minimal or no front fill", mood: "Mysterious, iconic, otherworldly", bestFor: ["Character reveals from shadow", "Angelic/demonic entrances", "Power-up silhouettes", "Eclipse magic"], keyToFillRatio: "Backlight dominant, 1:8 front", tags: { drama: "high", flattery: "low", mystery: "extreme" } },
    { id: "under_lighting", name: "Under Lighting", description: "Light source below the face casting unnatural upward shadows. Instinctively unsettling because it reverses how we normally see faces lit by the sky.", setup: "Light source below chin level — practical fire, cauldron glow, magical artifact", mood: "Sinister, unnatural, horrifying", bestFor: ["Dark magic rituals", "Horror reveals", "Villain monologues over glowing artifacts", "Campfire ghost stories"], keyToFillRatio: "Variable — often sole source", tags: { drama: "extreme", flattery: "low", mystery: "high" } },
    { id: "practical_only", name: "Practical / Motivated Only", description: "Scene lit exclusively by visible in-scene light sources — candles, torches, magical orbs, windows. Creates maximum authenticity and atmosphere.", setup: "All light from visible sources within the frame, supplemented carefully to maintain exposure", mood: "Authentic, immersive, intimate", bestFor: ["Candlelit rituals", "Tavern scenes", "Dungeon exploration by torchlight", "Magical artifact as sole light source"], keyToFillRatio: "Depends on practicals", tags: { drama: "medium", flattery: "low", mystery: "medium" } },
    { id: "top_lighting", name: "Top / Overhead Lighting", description: "Light directly above casting deep eye socket shadows and elongated facial shadows. Creates a sense of divine judgment or oppressive weight.", setup: "Light source directly overhead, minimal fill", mood: "Judgment, isolation, divine presence, oppression", bestFor: ["Divine intervention scenes", "Interrogation", "Prison/dungeon overhead shafts", "Chosen one moments"], keyToFillRatio: "8:1+", tags: { drama: "high", flattery: "low", mystery: "medium" } }
  ],

  lightQualities: [
    { id: "hard", name: "Hard Light", description: "Direct, unmodified light source creating sharp, defined shadows with crisp edges. High contrast between lit and shadow areas.", sources: "Direct sun, bare bulbs, focused spots, unmodified flash", mood: "Harsh, dramatic, confrontational, truthful" },
    { id: "soft", name: "Soft Light", description: "Diffused, scattered light creating gentle shadow transitions with soft edges. Low contrast, flattering, wrapping quality.", sources: "Overcast sky, large softboxes, bounce boards, diffusion frames", mood: "Gentle, romantic, dreamlike, safe" },
    { id: "diffused", name: "Diffused / Ambient", description: "Heavily scattered light with almost no directional quality. Fills space evenly, minimizing shadows entirely.", sources: "Heavy overcast, large scrims, ambient bounce in white rooms", mood: "Ethereal, otherworldly, liminal, uncertain" },
    { id: "specular", name: "Specular / Point Source", description: "Extremely small, intense light source creating razor-sharp shadows and brilliant highlights on reflective surfaces.", sources: "Bare LEDs, laser-like sources, tiny practicals, star effects", mood: "Magical, precise, dangerous, focused energy" }
  ],

  colorTemperatures: [
    { id: "candle", name: "Candlelight", kelvin: 1800, color: "#FF7E00", mood: "Ancient, ritual, intimate, primal", sources: "Candles, oil lamps, embers", magicTypeMatch: "ancient_elemental" },
    { id: "torch", name: "Torchlight / Firelight", kelvin: 2200, color: "#FF9900", mood: "Medieval, adventurous, warm danger", sources: "Torches, bonfires, fireplaces", magicTypeMatch: "ancient_elemental" },
    { id: "tungsten", name: "Tungsten Warm", kelvin: 2800, color: "#FFB347", mood: "Nostalgic, cozy, golden age", sources: "Incandescent bulbs, tungsten film lights", magicTypeMatch: "modern_urban" },
    { id: "halogen", name: "Halogen", kelvin: 3200, color: "#FFCC66", mood: "Neutral warm, professional, standard film", sources: "Halogen film lights, standard studio", magicTypeMatch: "modern_urban" },
    { id: "neutral", name: "Neutral White", kelvin: 4100, color: "#FFF4E0", mood: "Clinical, clean, transitional", sources: "Fluorescent, neutral LEDs", magicTypeMatch: "futuristic_tech" },
    { id: "daylight", name: "Daylight", kelvin: 5600, color: "#FFF8F0", mood: "Natural, truthful, clear, heroic", sources: "Midday sun, daylight-balanced LEDs, HMI", magicTypeMatch: "celestial_divine" },
    { id: "overcast", name: "Overcast / Cloudy", kelvin: 6500, color: "#E8F0FF", mood: "Somber, melancholic, muted, ominous", sources: "Cloudy sky, large cool-white diffusion", magicTypeMatch: "dark_forbidden" },
    { id: "blue_hour", name: "Blue Hour / Moonlight", kelvin: 9000, color: "#B0C4FF", mood: "Mysterious, supernatural, nocturnal, ethereal", sources: "Deep shade, moonlight simulation, CTB gels", magicTypeMatch: "dark_forbidden" }
  ],

  magicLightingPresets: [
    { id: "preset_ancient", magicSystemId: "ancient_elemental", keyLight: "Warm firelight (2200K) from practicals", fillLight: "Minimal — deep shadows with amber bounce", backLight: "Cool moonlight rim (9000K) for separation", practicalSources: "Torches, candles, glowing runes on stone", colorGel: "CTO (warm orange) on key, CTB (cool blue) on back", volumetric: "Ground fog lit by firelight, dust particles in torch beams", mood: "Ancient ritual in a sacred grove — warm islands of light surrounded by cool mysterious darkness" },
    { id: "preset_modern", magicSystemId: "modern_urban", keyLight: "Neutral to cool white (4100-5600K) from spell effects", fillLight: "Ambient city light — mixed temperatures, neon spill", backLight: "Hard orange sodium vapor edge light", practicalSources: "Spell circles as key light, glowing glyphs, city neon", colorGel: "Mixed gels creating color contrast", volumetric: "Urban haze catching spell light, rain with neon reflections", mood: "Controlled arcane precision against chaotic urban nightscape — order vs chaos in light" },
    { id: "preset_futuristic", magicSystemId: "futuristic_tech", keyLight: "Cool cyan-white (6500K+) from holographic sources", fillLight: "Low-level ambient blue from tech panels", backLight: "Sharp white LED edge for technical precision", practicalSources: "Holographic displays, energy conduits, glowing implants", colorGel: "Full CTB with cyan accents", volumetric: "Clean atmosphere with occasional energy particles, no organic haze", mood: "Sterile technological precision — every shadow has been engineered away except by design" },
    { id: "preset_robotic", magicSystemId: "robotic_cybernetic", keyLight: "Flickering neon mix (magenta/cyan) from signs and augmentations", fillLight: "Harsh industrial fluorescent (greenish cast)", backLight: "Hot magenta or electric blue rim from cybernetic glow", practicalSources: "Neon signs, cybernetic implant glow, sparking wires, HUD projections", colorGel: "Bi-color split — magenta/cyan opposing gels", volumetric: "Industrial steam, electrical sparks, digital interference patterns", mood: "Sensory overload in a world where flesh and machine blur — beauty in the breakdown" },
    { id: "preset_dark", magicSystemId: "dark_forbidden", keyLight: "Sickly green-tinged under-light (low intensity)", fillLight: "Near zero — oppressive darkness", backLight: "Cold purple rim from void energy (barely visible)", practicalSources: "Glowing corruption veins, dark artifacts with inverse glow (absorbing light)", colorGel: "Minus-green on key, deep purple on back", volumetric: "Thick black fog that absorbs rather than scatters light", mood: "Light itself is being consumed — the darkness isn't absence but presence" },
    { id: "preset_celestial", magicSystemId: "celestial_divine", keyLight: "Brilliant warm gold from above (5600K with warm gel)", fillLight: "Soft gold ambient wrap — shadows barely exist", backLight: "Intense white bloom creating halo effect", practicalSources: "The divine being IS the light source — golden radiance from within", colorGel: "Full CTO with gold diffusion", volumetric: "Heavy atmosphere for visible god rays, golden dust motes, lens bloom", mood: "Overwhelming divine radiance — mortals shield their eyes as heaven's light fills every shadow" }
  ],

  bodyMovements: [
    { id: "tai_chi_flowing", name: "Tai Chi / Flowing", origin: "Chinese martial arts philosophy", description: "Slow, continuous, circular movements that channel energy through the body like water. Every gesture flows seamlessly into the next, creating an unbroken stream of magical force.", keyPoses: ["Cloud hands — arms weaving circular patterns at chest height", "Wave rolling — full body undulation from feet to fingertips", "Crane stance — single leg balance with arms spread wide", "Push and pull — weight shifting with extended palms channeling energy"], rhythm: "Slow, continuous, meditative", pairedMagicSystems: ["ancient_elemental", "celestial_divine"], emotionalRegister: "Serenity, wisdom, deep connection to natural forces", soundAccompaniment: "Soft wind textures, sustained tonal drones, gentle chimes", promptKeywords: ["flowing gesture", "tai chi casting", "graceful spell movement", "water-like body movement", "meditative casting"], tags: { power: "medium", grace: "high", control: "high" } },
    { id: "martial_arts_precise", name: "Martial Arts / Precise", origin: "Various combat disciplines", description: "Sharp, explosive movements — strikes, blocks, and stances that channel magic through combat forms. Each gesture is a weapon, each stance a defensive ward.", keyPoses: ["Strike palm — forward thrust channeling energy blast", "Crane block — raised forearm deflecting incoming spells", "Horse stance — wide low stance gathering ground energy", "Spinning kick — full rotation releasing circular energy wave"], rhythm: "Staccato bursts with held positions", pairedMagicSystems: ["modern_urban", "futuristic_tech"], emotionalRegister: "Discipline, focus, controlled aggression, mastery", soundAccompaniment: "Sharp impacts, whooshing air cuts, snapping fabric", promptKeywords: ["martial arts magic", "combat casting", "strike gesture", "fighting spell stance", "warrior mage pose"], tags: { power: "high", grace: "medium", control: "high" } },
    { id: "conductor_orchestral", name: "Conductor / Orchestral", origin: "Musical direction", description: "Grand, sweeping arm movements that orchestrate magical forces as if conducting an invisible symphony. Fingers sculpt the air, arms direct streams of energy with theatrical precision.", keyPoses: ["Grand sweep — both arms arcing overhead directing energy streams", "Pinch and pull — fingers precisely manipulating individual magical threads", "Crescendo lift — arms rising from low to high building power", "Cut-off — sharp downward chop ending spell instantly"], rhythm: "Dynamic — building from pianissimo to fortissimo", pairedMagicSystems: ["modern_urban", "celestial_divine"], emotionalRegister: "Authority, creativity, theatrical command, artistic mastery", soundAccompaniment: "Orchestral swells, resonant harmonics, musical tones matching gestures", promptKeywords: ["conductor magic", "orchestral casting", "sweeping arm spell", "magical conductor", "symphony sorcery"], tags: { power: "high", grace: "high", control: "high" } },
    { id: "ritual_ceremonial", name: "Ritual / Ceremonial", origin: "Religious and occult ceremony", description: "Deliberate, symbolic gestures performed in specific sequences. Each movement has precise meaning — drawing sigils in air, ritual prostrations, sacred hand positions (mudras).", keyPoses: ["Sigil trace — finger drawing glowing symbols in the air", "Invocation arms — arms raised to sky calling down power", "Binding gesture — hands clasping together sealing a spell", "Prostration — kneeling with forehead to ground channeling earth energy"], rhythm: "Measured, ritualistic, rhythmic repetition", pairedMagicSystems: ["ancient_elemental", "dark_forbidden"], emotionalRegister: "Reverence, solemnity, ancient weight, sacrifice", soundAccompaniment: "Chanting drones, rhythmic percussion, resonant bells", promptKeywords: ["ritual casting", "ceremonial gesture", "sigil drawing", "occult movement", "sacred pose", "mudra spell"], tags: { power: "high", grace: "medium", control: "medium" } },
    { id: "tech_interface", name: "Tech Interface / Gestural", origin: "Sci-fi human-computer interaction", description: "Precise finger and hand movements manipulating holographic interfaces, swiping through data streams, and pinching/expanding virtual constructs. Minority Report meets magic.", keyPoses: ["Swipe and select — fingers flicking through holographic menus", "Pinch and expand — two-handed scaling of energy constructs", "Tap activation — precise finger touches activating nodes", "Drag and deploy — grabbing virtual objects and throwing them into reality"], rhythm: "Quick, precise, multi-touch fluidity", pairedMagicSystems: ["futuristic_tech", "robotic_cybernetic"], emotionalRegister: "Efficiency, technological mastery, casual power", soundAccompaniment: "UI chirps, haptic feedback clicks, data processing hums", promptKeywords: ["holographic interface gesture", "tech casting", "gestural magic", "virtual manipulation", "sci-fi hand movement"], tags: { power: "medium", grace: "medium", control: "high" } },
    { id: "primal_instinctive", name: "Primal / Instinctive", origin: "Animal behavior and raw emotion", description: "Raw, unrefined movements driven by emotion rather than training. Clawing at the air, screaming power into existence, full-body convulsions as magic rips through an untrained vessel.", keyPoses: ["Feral crouch — low stance with clawed hands and bared teeth", "Primal scream — head thrown back, chest open, releasing energy through voice", "Ground pound — slamming fists into earth sending shockwaves", "Writhing channel — body contorting as magic moves through unprepared flesh"], rhythm: "Chaotic, surging, unpredictable", pairedMagicSystems: ["dark_forbidden", "robotic_cybernetic"], emotionalRegister: "Desperation, rage, overwhelming power, loss of control", soundAccompaniment: "Guttural screams, bone cracks, raw distortion, animalistic growls", promptKeywords: ["primal magic", "feral casting", "raw power burst", "uncontrolled magic", "berserker spell"], tags: { power: "extreme", grace: "low", control: "low" } },
    { id: "meditation_still", name: "Meditation / Stillness", origin: "Contemplative traditions", description: "Near-total stillness where magic emanates from internal focus rather than external movement. Power radiates from concentration — a single opened eye can unleash a storm.", keyPoses: ["Lotus position — seated cross-legged with hands on knees channeling", "Standing meditation — feet planted, arms at sides, energy radiating outward", "Single gesture — one subtle hand movement (finger raise, palm turn) triggers massive effect", "Levitation — rising from seated position as power lifts the caster"], rhythm: "Near-still with rare, impactful movements", pairedMagicSystems: ["celestial_divine", "ancient_elemental"], emotionalRegister: "Inner peace, absolute mastery, transcendence, terrifying calm", soundAccompaniment: "Near silence, single resonant tone, breathing, subtle environmental response", promptKeywords: ["meditation magic", "still casting", "levitating mage", "calm power", "subtle gesture magic", "internal energy"], tags: { power: "extreme", grace: "high", control: "extreme" } }
  ],

  creatureShapes: [
    { id: "serpentine", name: "Serpentine", silhouetteDescription: "Long, sinuous body with no limbs or vestigial limbs. S-curves and coiling spirals define its movement and rest posture.", movementStyle: "Undulating, slithering, coiling, sudden strikes", sizeRange: "Medium to colossal", psychologicalEffect: "Primal fear, ancient wisdom, hypnotic fascination — the serpent archetype triggers deep instinctual responses", realWorldBasis: ["Snakes", "Eels", "Chinese dragons", "Sea serpents"], promptKeywords: ["serpentine creature", "dragon serpent", "coiling beast", "sinuous monster"], tags: { threat: "high", majesty: "high", alien: "medium" } },
    { id: "avian", name: "Avian", silhouetteDescription: "Broad wingspan, sharp beak or face, powerful taloned feet. Iconic spread-wing silhouette dominates the sky.", movementStyle: "Soaring, diving, hovering, sharp banking turns", sizeRange: "Small to massive", psychologicalEffect: "Freedom, divine messenger, predatory grace — creatures of air bridge heaven and earth", realWorldBasis: ["Eagles", "Ravens", "Bats", "Pterosaurs", "Phoenix mythology"], promptKeywords: ["winged creature", "avian beast", "flying monster", "eagle-like creature", "phoenix"], tags: { threat: "medium", majesty: "high", alien: "low" } },
    { id: "chimeric", name: "Chimeric / Hybrid", silhouetteDescription: "Composite of multiple animal forms — lion body with eagle head, serpent tail with mammalian torso. Deliberately unnatural combinations.", movementStyle: "Unpredictable — shifts between movement styles of component animals", sizeRange: "Medium to large", psychologicalEffect: "Wrongness, awe, impossibility — the mind struggles to categorize what it sees", realWorldBasis: ["Griffin", "Manticore", "Chimera", "Sphinx", "Hippogriff"], promptKeywords: ["chimera creature", "hybrid beast", "composite monster", "mythical hybrid", "impossible creature"], tags: { threat: "high", majesty: "medium", alien: "high" } },
    { id: "geometric_abstract", name: "Geometric / Abstract", silhouetteDescription: "Non-organic forms — crystalline polyhedra, fractal patterns, impossible geometry. Moves in ways that defy physics.", movementStyle: "Floating, rotating, folding, phase-shifting, tessellating", sizeRange: "Tiny to enormous", psychologicalEffect: "Cosmic horror, mathematical beauty, alien intelligence — something from beyond our dimension", realWorldBasis: ["Crystals", "Fractals", "Sacred geometry", "Lovecraftian entities"], promptKeywords: ["geometric creature", "crystal entity", "fractal being", "abstract monster", "eldritch geometry"], tags: { threat: "medium", majesty: "high", alien: "extreme" } },
    { id: "insectoid", name: "Insectoid", silhouetteDescription: "Segmented body, multiple limbs, compound eyes, mandibles, potential wings. Exoskeletal armor with chitinous textures.", movementStyle: "Skittering, clicking, sudden bursts, wall-crawling, swarming", sizeRange: "Tiny (swarm) to large", psychologicalEffect: "Revulsion, alien menace, overwhelming numbers — triggers deep arachnophobia and swarm anxiety", realWorldBasis: ["Beetles", "Spiders", "Mantises", "Scorpions", "Centipedes"], promptKeywords: ["insectoid creature", "bug monster", "chitinous beast", "spider creature", "swarm entity"], tags: { threat: "high", majesty: "low", alien: "high" } },
    { id: "aquatic_amorphous", name: "Aquatic / Amorphous", silhouetteDescription: "Fluid, boneless form that constantly shifts and reshapes. Tentacles, flowing membranes, bioluminescent patches.", movementStyle: "Flowing, engulfing, extending tendrils, shape-shifting", sizeRange: "Any — can compress or expand", psychologicalEffect: "Deep-sea dread, the unknown, suffocating embrace — fear of what lurks in dark water", realWorldBasis: ["Octopus", "Jellyfish", "Sea anemone", "Slime mold", "Kraken mythology"], promptKeywords: ["amorphous creature", "tentacle monster", "aquatic beast", "shapeless entity", "deep sea creature"], tags: { threat: "high", majesty: "medium", alien: "high" } }
  ],

  creatureMaterials: [
    { id: "ethereal_translucent", name: "Ethereal / Translucent", textureDescription: "Semi-transparent, ghostly material that light passes through. Internal structures dimly visible like frosted glass.", transparency: "High — background visible through creature", lightInteraction: "Refracts and scatters light, creating internal glow effects", decayOrGrowth: "Fades in and out of visibility, can become more or less solid", temperatureAssociation: "Cool to cold", soundSignature: "Whispered tones, glass harmonics, wind chimes", promptKeywords: ["ethereal creature", "translucent being", "ghostly entity", "spirit form", "spectral creature"], tags: { natural: "low", supernatural: "high", tech: "low" } },
    { id: "elemental_fire", name: "Elemental Fire", textureDescription: "Living flame — body composed of roiling fire with ember core, flowing magma skin, and corona of heat distortion.", transparency: "Low — dense fire core, transparent flame edges", lightInteraction: "Self-luminous, casts warm light, creates heat shimmer in surrounding air", decayOrGrowth: "Flares with anger, dims when calm, embers fall from body constantly", temperatureAssociation: "Extreme heat", soundSignature: "Roaring flames, crackling wood, hissing steam, explosive whooshes", promptKeywords: ["fire creature", "flame elemental", "magma beast", "living fire", "ember creature"], tags: { natural: "high", supernatural: "medium", tech: "low" } },
    { id: "elemental_ice", name: "Elemental Ice / Water", textureDescription: "Crystalline ice formations or flowing liquid held in coherent shape. Refractive, prismatic, with internal fracture lines.", transparency: "Medium — refractive and prismatic", lightInteraction: "Splits light into rainbows, internal prismatic reflections, surface glitter", decayOrGrowth: "Grows frost armor, sheds water droplets, freezes surroundings", temperatureAssociation: "Frigid cold", soundSignature: "Cracking ice, flowing water, crystalline tinkling, deep glacial groans", promptKeywords: ["ice creature", "frost elemental", "crystal beast", "water entity", "glacial creature"], tags: { natural: "high", supernatural: "medium", tech: "low" } },
    { id: "mechanical_steampunk", name: "Mechanical / Steampunk", textureDescription: "Brass, copper, and iron assemblages with visible gears, pistons, pipes, and steam vents. Industrial beauty in motion.", transparency: "Opaque — solid metal construction", lightInteraction: "Metallic reflections, warm brass tones, orange furnace glow from within", decayOrGrowth: "Rusts, gains patina, can be repaired/upgraded with new parts", temperatureAssociation: "Warm (steam/furnace powered)", soundSignature: "Gear grinding, steam hissing, metallic clanking, whistle blasts, clockwork ticking", promptKeywords: ["steampunk creature", "clockwork beast", "mechanical golem", "brass automaton", "steam-powered creature"], tags: { natural: "low", supernatural: "low", tech: "high" } },
    { id: "cosmic_nebula", name: "Cosmic / Nebula", textureDescription: "Body composed of swirling nebula gases, star clusters, and cosmic dust. The universe condensed into creature form.", transparency: "Semi-transparent — stars visible within body", lightInteraction: "Self-luminous with internal star points, emits nebula-colored light", decayOrGrowth: "Expands and contracts with breathing, star-births flash within", temperatureAssociation: "Absolute cold (vacuum) with hot star cores", soundSignature: "Deep cosmic drones, crystalline star tones, vast echoing resonance", promptKeywords: ["cosmic creature", "nebula entity", "star beast", "space creature", "celestial being", "galaxy creature"], tags: { natural: "low", supernatural: "high", tech: "low" } },
    { id: "shadow_void", name: "Shadow / Void", textureDescription: "Living darkness — absence of light given form. Edges blur into surrounding shadows, core is absolute black that absorbs all light.", transparency: "Inverse — absorbs light rather than transmitting it", lightInteraction: "Consumes light, creates darkness around it, light sources dim in proximity", decayOrGrowth: "Grows in darkness, shrinks in bright light, spreads like ink in water", temperatureAssociation: "Absence of temperature — a void", soundSignature: "Reversed sounds, bass drops, silence that has weight, muffled distant screams", promptKeywords: ["shadow creature", "void entity", "darkness monster", "living shadow", "light-consuming beast"], tags: { natural: "low", supernatural: "high", tech: "low" } },
    { id: "crystalline", name: "Crystalline / Mineral", textureDescription: "Body of living crystal — faceted surfaces, internal light refraction, mineral veins. Quartz, amethyst, obsidian, or diamond-like formations.", transparency: "Variable — from opaque obsidian to transparent quartz", lightInteraction: "Prismatic refraction, internal reflections, surface sparkle, can focus light into beams", decayOrGrowth: "Grows new crystal formations, shatters and reforms, mineral accretion", temperatureAssociation: "Cool, hard, geological time", soundSignature: "Glass-like ringing, crystalline chimes, grinding stone, harmonic resonance", promptKeywords: ["crystal creature", "mineral beast", "gemstone entity", "living crystal", "quartz golem"], tags: { natural: "high", supernatural: "medium", tech: "low" } },
    { id: "bioluminescent", name: "Bioluminescent / Organic", textureDescription: "Living organic tissue pulsing with internal bioluminescent patterns. Wet, membranous skin with glowing vein networks.", transparency: "Semi-transparent — internal organs and light channels visible", lightInteraction: "Self-luminous in patterns that shift with emotion, pulsing glow", decayOrGrowth: "Organic growth, shedding, regeneration, bioluminescence intensity reflects health", temperatureAssociation: "Warm, living body temperature", soundSignature: "Wet organic squelches, rhythmic pulsing, breathing, humming vibration", promptKeywords: ["bioluminescent creature", "glowing organism", "deep sea creature", "organic light beast", "living light"], tags: { natural: "high", supernatural: "medium", tech: "low" } }
  ],

  creatureBehaviors: [
    { id: "predatory_stalker", name: "Predatory Stalker", description: "Patient, calculating hunter that observes prey before striking with lethal precision. Every movement is purposeful, conserving energy for the kill.", aggression: 9, intelligence: 7, socialStructure: "Solitary or mated pairs", territoriality: "Large hunting territory, marks boundaries", signatureMoves: ["Freeze-and-assess pauses", "Low stalking approach", "Explosive ambush strike", "Prey testing feints"], soundPatterns: "Near-silent approach, low warning growl, explosive attack roar, satisfied feeding sounds", promptKeywords: ["predator creature", "stalking beast", "hunting monster", "ambush predator"], tags: { danger: "extreme", wisdom: "medium", chaos: "low" } },
    { id: "guardian_sentinel", name: "Guardian Sentinel", description: "Ancient protector bound to a location, artifact, or lineage. Immovable and patient for centuries, devastating when its charge is threatened.", aggression: 3, intelligence: 8, socialStructure: "Solitary — devoted to duty", territoriality: "Defends specific location or object absolutely", signatureMoves: ["Stone-still patience", "Warning display (making itself appear larger)", "Barrier creation", "Overwhelming defensive strikes"], soundPatterns: "Deep resonant breathing, warning rumbles, ground-shaking roar when provoked, protective humming", promptKeywords: ["guardian creature", "sentinel beast", "protector monster", "ancient guardian", "temple guardian"], tags: { danger: "medium", wisdom: "high", chaos: "low" } },
    { id: "trickster_shapeshifter", name: "Trickster / Shapeshifter", description: "Deceptive, playful, and unpredictable. May appear helpful before revealing dangerous true nature, or seem threatening while actually being benign.", aggression: 4, intelligence: 9, socialStructure: "Fluid — infiltrates other groups", territoriality: "No fixed territory — goes where opportunities exist", signatureMoves: ["Form mimicry", "Distraction displays", "False vulnerability", "Reality-bending pranks"], soundPatterns: "Mimicked voices, mocking laughter, discordant chimes, unsettling whispers", promptKeywords: ["trickster creature", "shapeshifter", "deceptive beast", "illusion creature", "mimic monster"], tags: { danger: "medium", wisdom: "high", chaos: "high" } },
    { id: "ancient_wise", name: "Ancient / Wise", description: "Being of vast age and accumulated knowledge. Moves deliberately, speaks rarely, and sees patterns in events spanning millennia. More likely to share wisdom than attack.", aggression: 1, intelligence: 10, socialStructure: "Solitary sage or small council of elders", territoriality: "Claims ancient sanctuaries", signatureMoves: ["Slow, deliberate head turns", "Long contemplative silences", "Subtle reality manipulation", "Knowledge-sharing rituals"], soundPatterns: "Deep resonant speech, thoughtful humming, ancient language whispers, cosmic vibrations", promptKeywords: ["ancient creature", "wise beast", "elder entity", "sage monster", "timeless being"], tags: { danger: "low", wisdom: "extreme", chaos: "low" } },
    { id: "swarm_hivemind", name: "Swarm / Hivemind", description: "Countless small units operating as one consciousness. Individually weak, collectively overwhelming. Moves like a fluid, thinks like a network.", aggression: 7, intelligence: 6, socialStructure: "Collective — no individuals, one mind", territoriality: "Expanding territory, consuming resources", signatureMoves: ["Wave attacks", "Shape formation", "Engulfing surround", "Sacrificial unit tactics"], soundPatterns: "Buzzing crescendo, clicking swarm communication, overwhelming chittering, sudden unified silence", promptKeywords: ["swarm creature", "hivemind entity", "collective beast", "insect swarm", "living cloud"], tags: { danger: "high", wisdom: "medium", chaos: "high" } },
    { id: "parasitic_corruptor", name: "Parasitic / Corruptor", description: "Attaches to or invades host organisms, corrupting them from within. Spreads through infection, turning allies into enemies. The body horror archetype.", aggression: 6, intelligence: 5, socialStructure: "Parasitic network through infected hosts", territoriality: "Spreads through biological territory — bodies as landscape", signatureMoves: ["Subtle initial infection", "Gradual host transformation", "Puppet control of infected", "Spore/tendril spreading"], soundPatterns: "Wet organic sounds, corrupted versions of host sounds, unsettling harmony of multiple voices", promptKeywords: ["parasitic creature", "corruption entity", "body horror beast", "infection monster", "corrupting organism"], tags: { danger: "extreme", wisdom: "low", chaos: "high" } },
    { id: "benevolent_healer", name: "Benevolent / Healer", description: "Gentle creature that restores and mends. Its presence calms, its touch heals, its song soothes. Rare and precious — often hunted for its restorative powers.", aggression: 0, intelligence: 7, socialStructure: "Small nurturing groups or bonded pairs", territoriality: "Gravitates toward places of pain or damage to heal", signatureMoves: ["Gentle approach", "Healing touch/aura", "Protective cocoon creation", "Empathic bonding"], soundPatterns: "Soft melodic humming, pure crystal tones, heartbeat synchronization, gentle purring", promptKeywords: ["healing creature", "gentle beast", "restorative entity", "nurturing monster", "magical healer"], tags: { danger: "none", wisdom: "high", chaos: "low" } }
  ],

  soundElements: [
    { id: "whoosh", name: "Whoosh / Swipe", category: "magic", description: "Fast air displacement sound marking the passage of magical energy through space. Conveys speed, direction, and force of spell movement.", frequencyRange: { low: 200, high: 12000 }, layeringPosition: "sweetener", organicVsSynthetic: 30, bestFor: ["Spell casting releases", "Energy projectiles", "Telekinetic movements", "Weapon swings"], creationTechnique: "Recorded rope/rod swings processed with pitch shifting and reverb" },
    { id: "impact_hit", name: "Impact / Hit", category: "magic", description: "The moment magical energy connects with its target. Combines sub-bass weight with high-end crackle for visceral satisfaction.", frequencyRange: { low: 30, high: 8000 }, layeringPosition: "accent", organicVsSynthetic: 40, bestFor: ["Spell impacts", "Shield blocks", "Magical collisions", "Power bursts"], creationTechnique: "Layered recordings of rock impacts, electrical arcs, and synthesized sub-bass drops" },
    { id: "riser_swell", name: "Riser / Swell", category: "transition", description: "Building tension sound that sweeps upward in pitch and intensity. Signals that power is accumulating before release.", frequencyRange: { low: 80, high: 16000 }, layeringPosition: "texture", organicVsSynthetic: 60, bestFor: ["Power charging", "Spell preparation", "Transformation build-up", "Dramatic tension"], creationTechnique: "Synthesized sweep with layered reversed cymbal and orchestral crescendo" },
    { id: "drone_sustain", name: "Drone / Sustain", category: "environment", description: "Continuous, evolving tonal bed that establishes the sonic atmosphere of magical spaces. Shifts subtly to reflect changing energy.", frequencyRange: { low: 20, high: 2000 }, layeringPosition: "base", organicVsSynthetic: 50, bestFor: ["Magical environments", "Sustained spells", "Enchanted locations", "Ritual atmospheres"], creationTechnique: "Granular synthesis of recorded metals, modified string drones, and analog oscillators" },
    { id: "chime_bell", name: "Chime / Bell", category: "magic", description: "Clear, ringing metallic tones that signify activation, completion, or divine presence. Pure frequencies that cut through any mix.", frequencyRange: { low: 500, high: 18000 }, layeringPosition: "sweetener", organicVsSynthetic: 20, bestFor: ["Spell activation", "Healing magic", "Celestial presence", "Magical notifications"], creationTechnique: "Recorded crystal bowls, bells, and chimes with harmonic enhancement and long reverb tails" },
    { id: "crackle_spark", name: "Crackle / Spark", category: "magic", description: "Electrical discharge and fracturing energy sounds. Irregular, unpredictable pops and snaps that convey volatile magical energy.", frequencyRange: { low: 1000, high: 20000 }, layeringPosition: "texture", organicVsSynthetic: 35, bestFor: ["Lightning magic", "Unstable spells", "Energy shields", "Electrical creatures"], creationTechnique: "Recordings of Jacob's ladders, Tesla coils, fire crackle, and processed static electricity" },
    { id: "rumble_sub", name: "Rumble / Sub-Bass", category: "environment", description: "Deep, felt-more-than-heard low frequencies that convey immense power, approaching danger, or the weight of ancient magic.", frequencyRange: { low: 15, high: 120 }, layeringPosition: "base", organicVsSynthetic: 45, bestFor: ["Earthquake magic", "Giant creature footsteps", "Dark power awakening", "Portal opening"], creationTechnique: "Slowed recordings of thunder, explosions, and industrial sounds combined with synthesized sub-bass" },
    { id: "whisper_breath", name: "Whisper / Breath", category: "creature", description: "Ghostly vocal fragments and breath sounds suggesting invisible presences, spirits, or psychic communication.", frequencyRange: { low: 300, high: 8000 }, layeringPosition: "texture", organicVsSynthetic: 15, bestFor: ["Ghost encounters", "Dark magic whispers", "Psychic communication", "Spirit realm sounds"], creationTechnique: "Heavily processed voice recordings with granular time-stretch, reversed segments, and spectral processing" },
    { id: "glitch_digital", name: "Glitch / Digital", category: "magic", description: "Stuttering, bit-crushed, and corrupted digital artifacts. Represents technological magic, reality glitches, or cybernetic malfunction.", frequencyRange: { low: 200, high: 20000 }, layeringPosition: "sweetener", organicVsSynthetic: 95, bestFor: ["Tech magic", "Reality glitches", "Cybernetic creatures", "Digital corruption"], creationTechnique: "Bit-crushing, granular buffer effects, circuit-bent electronics, and digital error simulation" },
    { id: "choir_ethereal", name: "Choir / Ethereal Vocal", category: "magic", description: "Angelic or otherworldly vocal harmonics — wordless singing that transcends language. Conveys divine intervention or cosmic scale.", frequencyRange: { low: 200, high: 14000 }, layeringPosition: "texture", organicVsSynthetic: 10, bestFor: ["Divine magic", "Celestial creatures", "Transcendent moments", "Ancient prophecy"], creationTechnique: "Recorded choir processed with granular synthesis, spectral manipulation, and vast convolution reverb" },
    { id: "metallic_ring", name: "Metallic Ring", category: "creature", description: "Resonant metal tones — the sound of magical alloys, enchanted weapons, and mechanical creatures. Sustained ringing with harmonic overtones.", frequencyRange: { low: 100, high: 12000 }, layeringPosition: "accent", organicVsSynthetic: 25, bestFor: ["Enchanted weapons", "Mechanical creatures", "Shield magic", "Armor transformation"], creationTechnique: "Recorded sword impacts, singing bowls, and metal resonance with harmonic enhancement" },
    { id: "nature_element", name: "Nature / Elemental", category: "environment", description: "Processed natural recordings — wind, water, fire, earth — sculpted to sound both natural and supernatural. The raw voice of the elements.", frequencyRange: { low: 30, high: 15000 }, layeringPosition: "base", organicVsSynthetic: 5, bestFor: ["Elemental magic", "Nature creatures", "Weather control", "Earth magic"], creationTechnique: "Field recordings of natural phenomena with spectral processing, pitch manipulation, and spatial enhancement" }
  ],

  colorPalettes: [
    { id: "teal_orange", name: "Teal & Orange Blockbuster", colors: ["#008B8B", "#E87E04", "#004040", "#FF6B00", "#002828"], description: "The dominant blockbuster palette. Complementary contrast between warm skin tones and cool shadows/environments. Visually striking and universally appealing.", technique: "Push shadows toward teal/cyan, warm midtones/highlights toward orange. Skin tone isolation in HSL.", mood: "Exciting, cinematic, larger-than-life", famousFilms: ["Transformers", "Mad Max Fury Road", "Blade Runner 2049"], magicSystemMatch: "futuristic_tech" },
    { id: "desaturated_grim", name: "Desaturated Grim", colors: ["#4A4A4A", "#6B6B6B", "#2C2C2C", "#8B8682", "#1A1A1A"], description: "Nearly monochrome with extremely muted color. Reality feels drained, hopeless, and raw. Occasional color elements pop dramatically.", technique: "Global saturation reduction (50-70%), crushed blacks, lifted shadows for milky quality.", mood: "Bleak, realistic, war-torn, desperate", famousFilms: ["Saving Private Ryan", "The Road", "Schindler's List"], magicSystemMatch: "dark_forbidden" },
    { id: "golden_warm", name: "Golden Warm Ancient", colors: ["#C9A84C", "#8B6914", "#DAA520", "#4A3728", "#FFF8DC"], description: "Rich amber and gold tones evoking candlelight, ancient manuscripts, and civilizations at their golden age. Shadows lean warm brown.", technique: "Warm color temperature (3200K look), golden lift in midtones, warm shadow tint.", mood: "Nostalgic, ancient, regal, warm", famousFilms: ["The Lord of the Rings", "Gladiator", "The Grand Budapest Hotel"], magicSystemMatch: "ancient_elemental" },
    { id: "neon_cyberpunk", name: "Neon Cyberpunk", colors: ["#FF00FF", "#00FFFF", "#FF1493", "#0000FF", "#0A0A0A"], description: "High-saturation neons against pure black. Magenta, cyan, and electric blue create a synthetic, hyper-saturated nightscape.", technique: "Crushed blacks, highly saturated highlights, split-toning with complementary neons.", mood: "Futuristic, dangerous, seductive, artificial", famousFilms: ["Blade Runner 2049", "John Wick", "Enter the Void"], magicSystemMatch: "robotic_cybernetic" },
    { id: "ethereal_pastel", name: "Ethereal Pastel", colors: ["#E8D5F5", "#D5E8F5", "#F5E8D5", "#F5D5E8", "#FFFFFF"], description: "Soft, lifted, dreamlike pastels with blown-out highlights and luminous skin. The world feels like a fading memory or heavenly vision.", technique: "Lifted shadows, reduced contrast, pastel tint in highlights, heavy diffusion/bloom.", mood: "Dreamlike, celestial, innocent, transcendent", famousFilms: ["The Tree of Life", "A Cure for Wellness", "Eternals"], magicSystemMatch: "celestial_divine" },
    { id: "deep_shadow", name: "Deep Shadow Horror", colors: ["#1A0000", "#330000", "#0D0D0D", "#4A0000", "#000000"], description: "Dominated by impenetrable darkness with only thin slivers of deep red or sickly green. Most of the frame is shadow.", technique: "Extreme underexposure, crushed blacks, minimal key light, monochromatic red or green push.", mood: "Terrifying, claustrophobic, evil, oppressive", famousFilms: ["The Exorcist", "Hereditary", "Crimson Peak"], magicSystemMatch: "dark_forbidden" },
    { id: "cosmic_vibrant", name: "Cosmic Vibrant", colors: ["#7B2FF7", "#00D4FF", "#FF6B9D", "#FFD700", "#0A0033"], description: "Deep space purples and blues punctuated by vibrant nebula colors. Saturated and vast, suggesting cosmic scale and wonder.", technique: "Deep blue/purple shadows, vibrant saturated highlights, contrast between vast dark and bright energy.", mood: "Wondrous, vast, psychedelic, cosmic", famousFilms: ["Guardians of the Galaxy", "Doctor Strange", "Thor Ragnarok"], magicSystemMatch: "celestial_divine" },
    { id: "monochrome_noir", name: "Monochrome Noir", colors: ["#FFFFFF", "#B0B0B0", "#606060", "#303030", "#000000"], description: "Pure black and white or near-monochrome. Maximum contrast between light and shadow. Timeless, graphic, and morally absolute.", technique: "Full desaturation or near-monochrome, high contrast, deep blacks, specular highlights.", mood: "Classic, moral clarity, stark, timeless", famousFilms: ["Sin City", "Schindler's List", "The Lighthouse"], magicSystemMatch: "ancient_elemental" }
  ],

  combinationRules: {
    synergies: [
      { elements: ["ancient_elemental", "tai_chi_flowing"], synergyScore: 9, description: "Natural harmony — flowing movements channel ancient earth energies with organic grace" },
      { elements: ["ancient_elemental", "crane"], synergyScore: 8, description: "Sweeping crane reveals ancient magical landscapes with cinematic grandeur" },
      { elements: ["modern_urban", "martial_arts_precise"], synergyScore: 9, description: "Disciplined combat forms create precise geometric spell constructs" },
      { elements: ["modern_urban", "whip_pan"], synergyScore: 8, description: "Fast transitions between spell effects match the rapid-fire nature of urban magic" },
      { elements: ["futuristic_tech", "tech_interface"], synergyScore: 10, description: "Perfect fusion — holographic gestures controlling technological magic feels completely natural" },
      { elements: ["futuristic_tech", "steadicam"], synergyScore: 8, description: "Smooth gliding camera matches the clean precision of tech-based magic" },
      { elements: ["dark_forbidden", "primal_instinctive"], synergyScore: 9, description: "Raw, desperate movements perfectly express magic that consumes its wielder" },
      { elements: ["dark_forbidden", "under_lighting"], synergyScore: 10, description: "Underlighting is the definitive lighting for dark magic — unnatural shadows match unnatural power" },
      { elements: ["celestial_divine", "meditation_still"], synergyScore: 10, description: "Divine power expressed through absolute stillness — overwhelming force from perfect calm" },
      { elements: ["celestial_divine", "crane"], synergyScore: 9, description: "Ascending crane shots mirror the heavenly origin of divine magic" },
      { elements: ["robotic_cybernetic", "handheld"], synergyScore: 8, description: "Handheld shake mirrors cybernetic glitching and unstable augmentation" },
      { elements: ["serpentine", "shadow_void"], synergyScore: 9, description: "Shadow serpent — darkness given sinuous, hunting form. Primal nightmare fuel" },
      { elements: ["avian", "cosmic_nebula"], synergyScore: 9, description: "Cosmic bird — wings of nebula gas trailing star-fire. Celestial messenger archetype" },
      { elements: ["geometric_abstract", "cosmic_nebula"], synergyScore: 10, description: "Fractal cosmic entity — impossible geometry filled with universe-stuff. Truly alien" },
      { elements: ["guardian_sentinel", "crystalline"], synergyScore: 9, description: "Crystal guardian — ancient mineral protector, beautiful and immovable" },
      { elements: ["predatory_stalker", "shadow_void"], synergyScore: 9, description: "Shadow predator — darkness that hunts. You can't flee what's everywhere" },
      { elements: ["trickster_shapeshifter", "ethereal_translucent"], synergyScore: 8, description: "Ghostly trickster — shifts between forms like smoke, never quite solid" },
      { elements: ["ancient_elemental", "golden_warm"], synergyScore: 9, description: "Warm golden tones perfectly evoke ancient magical civilizations at their peak" },
      { elements: ["anamorphic", "celestial_divine"], synergyScore: 9, description: "Anamorphic flares become divine light manifestations — lens artifacts as heavenly signs" },
      { elements: ["vertigo_effect", "dark_forbidden"], synergyScore: 10, description: "Reality warping visuals perfectly express the mind-bending horror of forbidden magic" },
      { elements: ["shallow", "portrait_telephoto"], synergyScore: 9, description: "Maximum subject isolation — the world dissolves into pure emotion around the character" },
      { elements: ["conductor_orchestral", "celestial_divine"], synergyScore: 9, description: "Conducting cosmic forces like a divine symphony — theatrical mastery of heavenly power" },
      { elements: ["ritual_ceremonial", "ancient_elemental"], synergyScore: 10, description: "The most natural pairing — ancient magic demands ancient ritual to channel it" },
      { elements: ["drone_aerial", "avian"], synergyScore: 9, description: "Aerial perspectives naturally showcase winged creatures in their element" },
      { elements: ["rembrandt", "ancient_elemental"], synergyScore: 8, description: "Painterly lighting evokes the artistic grandeur of ancient magical traditions" }
    ],
    conflicts: [
      { elements: ["handheld", "meditation_still"], severity: "moderate", description: "Chaotic camera undermines the stillness that defines meditation casting. Consider: handheld on observers, still on meditator.", suggestion: "Use handheld for reaction shots of observers, locked-off or steadicam for the meditator" },
      { elements: ["futuristic_tech", "ritual_ceremonial"], severity: "mild", description: "Ritualistic movements feel anachronistic with tech magic. Works if deliberately contrasting old traditions with new power.", suggestion: "Frame it as ancient programming language — ritual becomes code-incantation" },
      { elements: ["celestial_divine", "under_lighting"], severity: "strong", description: "Divine light comes from above — underlighting contradicts the fundamental visual language of heavenly power.", suggestion: "Reserve underlighting for fallen divine beings or corrupted celestial entities" },
      { elements: ["ancient_elemental", "glitch_digital"], severity: "strong", description: "Digital glitch sounds clash with organic ancient magic. Unless depicting ancient magic being corrupted by technology.", suggestion: "Only combine if the story involves tech corrupting nature — make the conflict the point" },
      { elements: ["benevolent_healer", "predatory_stalker"], severity: "strong", description: "Healing nature directly contradicts predatory behavior — creates confusing creature identity.", suggestion: "A creature that stalks the wounded to heal them could be compellingly unsettling" },
      { elements: ["ultra_wide", "portrait_telephoto"], severity: "moderate", description: "Opposite lens choices — can't use both simultaneously. Choose based on whether you prioritize environment or character.", suggestion: "Cut between them — wide for establishing the magic, telephoto for emotional reaction" },
      { elements: ["tilt_shift", "handheld"], severity: "moderate", description: "Tilt-shift requires precise framing that handheld movement disrupts. The miniature effect breaks down with shake.", suggestion: "Use tilt-shift for establishing miniature views, handheld for ground-level action" },
      { elements: ["neon_cyberpunk", "ancient_elemental"], severity: "mild", description: "Neon color grading clashes with the organic earthiness of ancient magic. Effective only if worlds collide.", suggestion: "Works for fish-out-of-water stories — ancient mage in modern cyberpunk city" },
      { elements: ["deep_shadow", "celestial_divine"], severity: "strong", description: "Near-total darkness contradicts divine radiance. Fundamentally opposing visual languages.", suggestion: "Combine only for eclipse mythology or divine beings descending into the underworld" },
      { elements: ["swarm_hivemind", "meditation_still"], severity: "moderate", description: "Swarm chaos conflicts with meditative stillness. The swarm has no individual consciousness to meditate.", suggestion: "The swarm achieves collective stillness — all units freeze simultaneously in eerie synchronization" }
    ],
    moodOutputs: {
      epic: { requiredTags: ["scale:large", "energy:high"], description: "Sweeping scope meets surging energy — armies clash, mountains crumble, and the fate of worlds hangs in the balance" },
      intimate: { requiredTags: ["scale:small", "intimacy:high"], description: "The world narrows to a single connection — two souls, one shared breath, magic as personal as a heartbeat" },
      mysterious: { requiredTags: ["mood:mysterious", "mystery:high"], description: "Shadows hold secrets and every corner hides revelation — the audience leans forward, searching for answers in the darkness" },
      terrifying: { requiredTags: ["mood:dark", "intensity:high"], description: "Dread saturates every frame — something terrible approaches and escape seems impossible. Pure cinematic horror." },
      triumphant: { requiredTags: ["mood:heroic", "energy:high"], description: "Victory earned through sacrifice — the hero rises, the music swells, and light conquers darkness at last" },
      melancholic: { requiredTags: ["mood:sad", "energy:low"], description: "Beautiful sadness — magic fading, worlds ending, the bittersweet ache of what was lost and can never return" },
      chaotic: { requiredTags: ["energy:high", "control:low"], description: "Controlled chaos — reality fractures, magic runs wild, and the audience cannot predict what comes next" },
      serene: { requiredTags: ["energy:low", "mood:peaceful"], description: "Perfect stillness — magic as meditation, nature in harmony, the calm eye of the storm" },
      ominous: { requiredTags: ["mood:dark", "energy:low"], description: "Something wicked this way comes — slow, inevitable dread building before the storm breaks" },
      awe_inspiring: { requiredTags: ["scale:large", "mood:wonder"], description: "Breathtaking scale meets wonder — the audience gasps as the impossible becomes visible" }
    },
    promptTemplates: [
      "{magicStyle} magic, {bodyMovement} casting pose, {cameraMovement} camera movement, {lens} lens, {lightingPattern} lighting, {colorGrade} color grading, cinematic, fantasy film still, 8K, photorealistic",
      "A {creatureShape} {creatureMaterial} creature with {creatureBehavior} behavior, {lightingPattern} lighting, {lens} lens, {colorGrade} color palette, dark fantasy concept art, highly detailed",
      "Cinematic {cameraMovement} shot of a sorcerer performing {bodyMovement} gestures, {magicStyle} energy swirling around them, {lightingPattern} dramatic lighting, {colorGrade} color grade, film grain, anamorphic"
    ]
  }
};
